### PR TITLE
Added time partitioning

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@mac2000 can you confirm this is everything we need to add? If thats the case then @lnklnklnk can you please merge this with master.

**Comment by marchenko1985** [comment]
@MarcoPorracin seems like everything is OK, but still original question is it by desing (I mean that there is different approaches for this stuff in BQ) and should it be by default or considered by user (e.g. will it broke something somewhere) unfortunately I really do not know answers for this questions, but we are using similar code and everything is ok

Hope that helps

**Comment by ghost** [comment]
Well @mac2000 im testing it myself then. 

google_bigquery

I don't think this a bad approach for the problem. If you ever had Analytics 360 linked with BQ you know they use the same method.

google_bigquery

**Comment by marchenko1985** [comment]
no one saying it is bad or good, even more we are using it in same way, the question is will it brake something if it will be turned on by default or not

**Pull request closed without merging**
